### ISSUE TITLE
RFC: structured, Ruby-mapped codegen diagnostics (don't defer ill-typed emits to a gcc error on out.c)

### ISSUE THREAD

**Issue by OriPekelman** [matz/spinel#1338]
## Motivation

Spinel's analysis surfaces are machine-readable (`--emit-rbs`, the emit-0 warnings, and the symbol map proposed in #1334). But **codegen failures are not**: when an emitted C construct is ill-typed, the only signal is a `gcc`/`cc` error on the generated `out.c` — with no mapping back to Ruby. Tooling and users are left reverse-engineering machine-generated C.

Concrete, all from the last few days of compatibility triage (each surfaces *only* as a `cc` error on `out.c`):

| reason | what the user sees today |
|---|---|
| a `Class` value boxed as int | `out.c:68: incompatible type for argument 1 of 'sp_box_int'` (#1337) |
| a stdlib class in an ivar | `out.c:20: unknown type name 'sp_Mutex'` (#1305) |
| reopening `class Object` | `out.c:18: redefinition of 'struct sp_Object_s'` (#1306) |
| a branch local in a lambda | `out.c: 'lv_x' undeclared` (#1315) |
| `&blk` + `block_given?` | `out.c: 'lv_blk' undeclared` (#1316) |

None of these names a Ruby file/line; `lv_x` / `sp_Mutex` / `sp_box_int` mean nothing to a gem author, and a tool can only grep the gcc text heuristically.

## Proposal

A **structured codegen-diagnostics** mode — e.g. `spinel --emit-diagnostics` (or folded into a `--json` build report) — where the codegen pass reports the errors *it* can detect, classified and mapped to Ruby source via the same machinery as the #1334 symbol→Ruby map:

```json
{ "stage": "codegen",
  "reason": "incompatible-type",          // unknown-type | redefinition | undeclared-ident | incompatible-type | arg-count
  "ruby_file": "app.rb", "ruby_line": 5,
  "detail": "Class value (RuntimeError) used where Integer expected; boxed via sp_box_int",
  "c_symbol": "sp_box_int" }
```

Where Spinel emits a construct it knows is ill-typed (a `Class` into an int-boxer, a `sp_<Stdlib>` type it never defines, a synthesized local it references but doesn't declare, a duplicate builtin struct), it should record a Ruby-level diagnostic rather than leaving `cc` to fail on `out.c`.

## Why it's worth it

- **Users** get a Ruby-level error ("`RuntimeError` used as an Integer at `app.rb:5`") instead of a gcc error in generated C.
- **Tooling** (`spinel-doctor` / `spinel-reduce`, [spinel-dev#10](https://github.com/OriPekelman/spinel-dev/issues/10)) can target and delta-debug codegen errors directly — today the doctor's analysis-only legs report these programs as `clean`, so the bulk of real compatibility breakage is invisible to it.
- Pairs naturally with #1334 (symbol→Ruby map) — this is its codegen-error counterpart; together they make every Spinel failure traceable to a Ruby line.

Scope note: not asking Spinel to *fix* these miscompiles here (those are separate issues, e.g. #1337/#1305/#1306) — only to **report** the ones it can already detect at emit time, structured and Ruby-mapped, instead of deferring to `cc`.

**Comment by matz** [comment]
Thanks for this. I went through the five examples and the proposed mechanism, and shipped a different approach. The reasoning:

**At the current type-inference precision, the emit-time-prediction premise doesn't hold for most of these.** The proposal asks codegen to "report the ones it can already detect at emit time." But for the mis-inference cases (the `sp_box_int` row, #1337: an int-typed container holding a `Class`), codegen does *not* know it is ill-typed. It genuinely believes the value is an Integer, which is exactly why it emits the int path. The C type error exists *because* codegen's type model was wrong, and a wrong model cannot simultaneously know it is wrong. With the current precision, detecting the mismatch is the same act as fixing it: if codegen knew a `Class` was flowing into `sp_box_int`, it would emit `sp_box_class` (the fix) and there would be no error left to report. So a structured emit-time-diagnostics mode would stay silent for precisely the cases that motivate it. (Empirically, all five examples got *fixed* in inference/codegen over the last couple of days, not *reported*, which is the response mis-inference actually wants.)

The exceptions are the cases where codegen *does* have authoritative knowledge: a genuinely-unsupported stdlib class (`sp_Mutex`, #1305) and a builtin-struct redefinition (#1306). There an emit-time guard with a clean "Mutex is not supported (app.rb:5)" is feasible and strictly better than a gcc error. That part of the RFC is right, and I have it noted as follow-up.

**What shipped instead reaches the goal without predicting anything.** The C compiler already produces `out.c:line` errors, and codegen already has a Ruby line map (the `#line` machinery `--debug` emits). So rather than foresee errors at emit time, codegen now emits `#line N "src.rb"` directives in normal optimized builds and lets the C compiler itself attribute the error to the Ruby line:

```
before:  out.c:72:19: error: invalid operands to binary << (have 'sp_Set' {aka struct sp_Set_s} ...)
after:   app.rb:6:19: error: invalid operands to binary << (have 'sp_Set' {aka struct sp_Set_s} ...)
```

(`@seen << x` on line 6, a `Set` stored in an ivar, which still miscompiles today.) It is a front-end-only diagnostic, decoupled from `--debug`'s -O0/-g cost: the optimizer never sees the directives and the binary is identical modulo line attribution, so it is on by default (opt out with `--no-line-map`). This catches the whole tail, including the mis-inference errors codegen cannot foresee, and it closes the `spinel-doctor` "reports clean" gap directly: a full build now surfaces `app.rb:N: error`, a real Ruby-anchored breakage, instead of nothing.

Two honest limits:

- `#line` reaches the statement stream, so it maps expression-level errors (the `sp_box_int` / undeclared-local family). Errors emitted in the hoisted struct/typedef region (#1305 `unknown type 'sp_Mutex'`, #1306 `redefinition`) still report against the generated C. Those are the category-B cases that want the emit-time guards above.
- The line is exact; the column is the C column relabeled onto the Ruby line (`#line` carries no column), so treat the column as approximate.

Net: a structured Ruby-level classification on top of this is still possible, but it is no longer load-bearing, since the native `app.rb:N: error` line is already tool-parseable. Shipped in ea60d5f. Does this cover what you need for the doctor / reduce tooling?

**Comment by OriPekelman** [comment]
This is the right call, and the reasoning is exactly right: a wrong type model can't self-report, so for the mis-inference tail "detect == fix" — and the five examples getting *fixed* rather than reported is the proof. (Confirmed on my side too: `h[:a] = String` now compiles — inference picks `SymPolyHash` and boxes the Class as poly — where a few days ago it was the `sp_box_int` incompatible-type. So my own repro for that row is now stale, which is the happy outcome.)

**The `#line`-on-by-default approach covers what the doctor/reduce tooling needs — and I've wired doctor to consume it.** doctor's codegen leg (spinel-dev#10) compiles the emitted C and was already classifying the first `cc` diagnostic; it now also **parses the `app.rb:N` attribution out of the error** and reports it (`codegen.source` in `--json`, `C build FAILS at app.rb:6 [incompatible-type] on sp_…` in the human report). So a build failure points at the Ruby line, not just the C symbol, and `spinel-reduce` ddmins it to the minimal trigger. Backward-compatible: pre-`#line` builds emit `out.c:N`, so `source` is null and it falls back to the symbol (no regression). The "doctor reports clean" gap is now closed from both ends — doctor compiles the C *and* the error is Ruby-anchored.

**One thing I should verify with you, because doctor's leg compiles separately from `-o`.** Your example is the full `spinel -o` path. doctor runs `spinel -c` (emit C) and then `cc -c` the result itself (compile-only, so it skips link/FFI-object noise). For doctor to inherit the `app.rb:N` attribution, the `#line` directives need to be in the **`-c` / `--emit-c` output**, not only injected on the `-o` cc invocation. Are they? If `-c` carries them, doctor gets the Ruby line for free (I've tested the parse against your exact format and it lands `app.rb:6`); if they're only on the `-o` path, I'll point doctor's leg at `spinel -o` instead. Either way it works — just want to match doctor's compile step to where the directives live.

**Category-B (the hoisted region) lines up with your follow-up.** Your two honest limits are exactly the cases where doctor's leg still only has the C symbol — `unknown type 'sp_Mutex'` (#1305) and `redefinition of 'struct sp_Object_s'` (#1306) report in the struct/typedef region that `#line` doesn't reach, so `codegen.source` is null there. Those are precisely where an emit-time guard with `Mutex is not supported (app.rb:5)` would give doctor a real Ruby line for the category-B cases too — so I'd happily consume that guard when you get to it, and it slots into the same `codegen.source` field. Shipped my side in `f5c369a`.

**Comment by OriPekelman** [comment]
Answering my own open question, verified on a fresh `master` build (`c3711e0`, has `ea60d5f`): **`spinel -c` carries the `#line` directives by default**, so doctor's leg gets the attribution for free — no need to switch it to `-o`.

```
$ spinel -c app.rb -o x.c        # 2 directives: #line 2 "app.rb", #line 4 "app.rb"
$ # doctor's codegen leg: cc -c x.c  →  app.rb:N: error:
```

End-to-end through doctor on a still-failing statement-level case (`@seen << x` with a `Set` ivar):
```
codegen: {error_class: invalid-operands, symbol: sp_Set,
          message: "invalid operands to binary << (have 'sp_Set' …)",
          source: "app.rb:7"}        # ← the #line attribution, exact Ruby line
verdict: codegen-error
```

So the "doctor reports clean" gap is fully closed: the leg compiles the emitted C *and* anchors the failure to the Ruby line, with no `--debug`/`-O0` cost (the directives ride the normal optimized build, as you designed). The only cases still showing the generated-C location are the hoisted-region ones (`unknown type 'sp_Mutex'` #1305, `redefinition` #1306) — `source` is null there, which is the precise signal for where your category-B emit-time guards would add the Ruby line. Thanks — this landed cleanly for the tooling.

**Comment by matz** [comment]
Closing this out: both halves of the Ruby-mapped-codegen-diagnostics goal now land.

- **cc-deferred errors** → already covered by the `#line`-on-by-default machinery (ea60d5f): an ill-typed emit reports as `app.rb:N: error` via the C compiler, which `spinel-doctor`/`spinel-reduce` parse into `codegen.source` (you verified this end-to-end in `c3711e0`).
- **emit-time guards** (the follow-up I'd noted — where codegen *does* have authoritative knowledge it can't emit a construct) → 47f12e5: `unsupported(...)` now prepends the source position the parser stamps (the same `node_line`/`node_file` the `#line` directives use), so instead of an opaque `node 25 (CallNode <<)` you get:

```
spinel: app.rb:7: unsupported call: node 25 (CallNode `<<`) recv=InstanceVariableReadNode/...
```

It's generic across every `unsupported` site, so the category-B cases that the hoisted-region `#line` couldn't reach (a Set/Mutex op rejected at emit, etc.) now carry the Ruby line for doctor's `codegen.source` too. Falls back to the bare node form when a position wasn't stamped.

So every Spinel codegen failure -- cc-deferred or codegen-detected -- is now anchored to a Ruby line. The structured-JSON classification on top of this stays possible but, as discussed, isn't load-bearing (the `file:line` line is already tool-parseable). If a specific category-B case wants a *clean message* rather than the diagnostic-detail form (e.g. `Mutex is not supported (app.rb:5)` instead of `unsupported call ...`), that's a per-construct refinement worth its own issue. Thanks for the framing — the "detect == fix for the mis-inference tail, report for the genuinely-unsupported" split was exactly right.
