### ISSUE TITLE
A `&blk` method with only block-less callers has no entry for a poly-receiver call since d15f227a (NoMethodError)

### ISSUE THREAD

**Issue by rubys** [matz/spinel#4492]
Since d15f227a (\"A `blk.nil?` test does not let the block escape, so the helper inlines\", the #4477 fix), a method whose `&blk` is only `call`ed under `blk.nil?` inlines at its call sites. When every call site is block-less, nothing keeps a standalone entry — and a call through a poly receiver, which dispatches by class to a callable symbol, finds no arm and raises `NoMethodError` for a method the class plainly defines.

```ruby
# A method whose &blk is only called-unless-nil inlines since d15f227a. When
# every call site is block-less, nothing keeps a standalone entry, and a
# call through a poly receiver has no arm to dispatch to: NoMethodError.
class Req
  attr_accessor :body
end

class Http
  def initialize(host)
    @host = host
  end

  def request(req, &blk)
    res = "#{@host}:#{req.body}"
    blk.call(res) unless blk.nil?
    res
  end
end

slots = { "h" => Http.new("example.test") }
req = Req.new
req.body = "hello"
puts slots["h"].request(req)
```

```
$ ruby blk_poly2.rb
example.test:hello

$ spinel blk_poly2.rb -o t && ./t      # master 1fe20889, and d15f227a itself
undefined method 'request' for an instance of Http (NoMethodError)

$ spinel blk_poly2.rb -o t && ./t      # d15f227a~1
example.test:hello
```

Bisected on campfire's `test/models/webhook_test.rb`: `d15f227a` is the first bad commit; `d0feb620` good. Adding one call site with a block (`slots["h"].request(req) { |r| … }`) makes it pass again, which is the mechanism: that site keeps the standalone entry the poly dispatch needs.

Where it lands: the runtime's `Net::HTTP#request(req, &blk)` (spinel-net-http's shape, `blk.call(res) unless blk.nil?`) reached through `Net::HTTP.new(host, port).tap { … }` in campfire's `Webhook#post`. The published lane at <https://roundbench.showcase.party/campfire-suite/> went 275 → 269 of 288 with spinel `9f19cbd3` (`webhook_test` 0/6, `user_bot_test` 3/4, all `undefined method 'request' for an instance of Net::HTTP`); the app is pinned, the compiler is not.

The commit message names the neighbouring hazard for `if blk` (\"forwarders called without a block whose `inner(&blk)` then names a block no inline site declares\"); this is the other edge of the same decision — a poly dispatch site is a caller the inline pass cannot see, so a candidate it selects must still have a symbol to call.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01GTHXBDXH9EohRcenKAUSfF

**Comment by matz** [comment]
Fixed in 6dfd268e. pf_wanted asked for the proc form only when a poly-receiver call carried a block; a blockless call through a poly receiver is a caller the inline pass cannot see all the same, so it now asks for any poly-receiver call naming the method. The proc form is the arm the dispatch needs, and its block parameter is NULL there, which is what `blk.nil?` already tests.

The probe around it turned up two neighbours, fixed in the same commit: the inline yield expansion over a poly receiver did not build for a by-value class (self is the struct, not a pointer), and a yield through a proc parameter (proc form, lowered yielder, forwarded &blk) answered nil for a NULL proc where Ruby raises LocalJumpError. test/poly_dispatch_blockless_blk_method.rb covers the three. On campfire the generated C gains the request_pf arm for Net::HTTP#request in the dispatch you named, plus Cache#fetch, Pathname#find and Fetch#request.

**Comment by matz** [comment]
Follow-up in 9e7c4b6a: with the proc form as the arm, the dispatch was still reading a candidate's parameters against the method's original scope (untyped, since it only ever inlined), so campfire's `cookies.fetch("flash_notice", "")` took the Cache#fetch arm with a String for its Hash parameter and the C build stopped. The arm now reads the proc form's own parameters; campfire builds and serves again.
