### ISSUE TITLE
promote: a block_given? else-arm emits sp_RbVal into an sp_int slot and the C build fails (bisected to b29ec9a7)

### ISSUE THREAD

**Issue by makenowjust** [matz/spinel#4659]
Under `--int-overflow=promote`, this stops the C build on master:

```ruby
def maybe_yield(x)
  if block_given?
    yield x
  else
    x * 2
  end
end
puts maybe_yield(5)
maybe_yield(5) { |n| n * 3 }
```

```
reg.rb:5: error: assigning to 'sp_int' (aka 'long') from incompatible type 'sp_RbVal'
spinel: C compilation failed
```

Line 5 is the `else` arm. The method's inline result slot is declared `sp_int`, and the arm emits `sp_poly_mul(...)`, which is an `sp_RbVal`:

```c
sp_int _t3 = 0;
...
  _t3 = sp_poly_mul(lv__y2_x, sp_box_int_or_nil(2LL));
```

`--int-overflow=raise` is unaffected — it compiles and prints `10`.

**Bisected to b29ec9a7** ("Enumerable#each_with_object is written in Ruby and compiled with the program"). Its parent `4620b215` compiles the same program and prints `10`.

Two tests in the corpus go with it, both failing to build in promote mode from that commit and passing at its parent:

- `test/block2.rb:7`
- `test/block_given_tail_typed_per_call.rb:28`

Both are the same shape: a `block_given?` guard whose `else` arm is arithmetic on the parameter, called once without a block and once with one. Writing `each_with_object` in Ruby presumably brings a new yielding method into every program's analysis, which moves what the parameter's type unifies to — the arm is then poly where the slot was settled as `sp_int`.

The promote lane is not in CI, which is why this landed green.

**Comment by matz** [comment]
Fixed in 273cb8ac. The promote pass widens every Integer local and return to a boxed slot after the fixpoint, and the blockless answer of an `if block_given?` tail (Scope.ret_noblock, new in b29ec9a7) was not on that list, so the inline result slot stayed sp_int while the else arm ran on the widened parameter. It now widens under the same exclusions as the return. Your program prints 10 in promote mode, and `test/block2.rb` and `test/block_given_tail_typed_per_call.rb` build there again.

Test: `test/block_given_else_arm_overflow_modes.rb`, checked under both modes by hand since the promote lane is not in CI.

**Comment by makenowjust** [comment]
A second one of the same shape, from a different commit in the same family.

`test/yield_result_through_forwarding_block.rb` also stops the C build under `--int-overflow=promote`:

```
test/yield_result_through_forwarding_block.rb:10: error: passing 'sp_RbVal' to parameter of incompatible type 'const char *'
test/yield_result_through_forwarding_block.rb:10: error: passing 'sp_RbVal' to parameter of incompatible type 'sp_float' (aka 'double')
```

**Bisected to 50e2d7bf** ("Enumerable#partition and #group_by are written in Ruby"). Its parent `fe2b4177` compiles it. `raise` mode is unaffected there too.

So on current master (`bbfe1ee5`) three corpus tests fail to build in promote mode, from two commits:

| test | commit |
|---|---|
| `block2` | b29ec9a7 |
| `block_given_tail_typed_per_call` | b29ec9a7 |
| `yield_result_through_forwarding_block` | 50e2d7bf |

Both commits move a library method from C into compiled Ruby, which brings another yielding method into every program's analysis and shifts what a yield value unifies to. The promote lane is not in CI, so each landed green.

(For reference, the same-machine promote failure set went from 104 entries to 107 across these commits; the third delta, `issue_2902`, compiles fine on its own and is a parallel-run flake.)
