### ISSUE TITLE
## D. Range#minmax → C Compilation Error

### ISSUE THREAD

**Issue by neidiom** [matz/spinel#1217]
**Root cause:** Analyzer (`spinel_analyze.rb:5499`) returns `"tuple:int,int"` for `minmax`. Codegen has no handler for `minmax` in `compile_range_method_expr` (line 21974). The fallback emits a variable declaration with `sp_Tuple_int_int*` and tries to inspect `_t->_0` — but `sp_Tuple_int_int` struct is never defined in the runtime. `Range#min` and `Range#max` work individually (lines 21975, 21986).

```ruby
# test_range_minmax.rb
puts (1..10).minmax.inspect
puts (1..10).min
puts (1..10).max
```

| Test | CRuby | Spinel | Verdict |
|------|-------|--------|---------|
| `minmax` | `[1, 10]` | `💥 C error: unknown type name 'sp_Tuple_int_int'` | ✗ |
| `min` | `1` | `1` | ✓ |
| `max` | `10` | `10` | ✓ |

**Fix:** Add `minmax` to `compile_range_method_expr` — build a tuple struct from `min` and `max` and register the tuple type, or just emit `sp_minmax_tuple(rc)`.
