### ISSUE TITLE
A bare call to a method the enclosing class also defines refuses the C build: declared Hash meets sp_RbVal

### ISSUE THREAD

**Issue by webit-wagner** [matz/spinel#4600]
A bare call to a method the enclosing class also defines now refuses the C build where
its declared return type meets a typed assignment target.

## Repro

`probe.rb`:

```ruby
class Base
  def attributes
    {}
  end

  def snapshot
    @snap = attributes
    nil
  end
end

class Post < Base
  def attributes
    { "a" => "b" }
  end
end

x = Post.new
x.snapshot
p x.attributes
```

`sig/probe.rbs`:

```rbs
class Base
  @snap: Hash[String, untyped]
  def attributes: () -> Hash[String, untyped]
  def snapshot: () -> void
end

class Post < Base
  def attributes: () -> Hash[String, untyped]
end
```

```
spinel --rbs sig -O 0 probe.rb -o probe
```

```
probe.rb: In function ‘sp_Base_snapshot’:
probe.rb:7: error: incompatible types when assigning to type ‘sp_StrPolyHash *’ from type ‘sp_RbVal’
spinel: C compilation failed
```

CRuby prints `{"a" => "b"}`.

## Bisected

| commit | result |
| --- | --- |
| `5680dddd` (parent) | compiles, prints `{"a" => "b"}` |
| `a4ac0fd3` — *The enclosing chain's own method answers before any Kernel builtin* (#4593) | the error above |

`git bisect` over the 26 commits between two CI runs of
[roundhouse](https://github.com/rubys/roundhouse), whose `toolchain-spinel` /
`compare-spinel` / `smoke-spinel` jobs build spinel from `master` unpinned and went red
between them. It reaches this on its own `runtime/active_record/connection.rb`, where a
`Base#attributes` returning `{}` is overridden per model and read through a receiverless
call — the same shape as above.

## What stands out

The change is about names that collide with a **Kernel builtin** — `trap`, `format`,
`Hash`, `sleep` and the rest of the list in its message. `attributes` is not one of
them, so whatever the new analysis rule does, it is not confined to the collision it was
written for.

A hypothesis, offered as one because I have not read the rule: the difference between
the two methods here is that `Base#attributes` returns `{}`, a hash with no element
types, while the signature declares `Hash[String, untyped]`. If the rule now answers a
bare call from the enclosing class's own BODY where it previously took the declared
type, that would produce exactly this — a poly value meeting a typed slot. The ivar is
declared too, so both ends of the assignment have a type and only the call in the middle
lost one.

Happy to test a patch against the repro and against roundhouse's suite.

**Comment by matz** [comment]
Fixed in 5d23d1e1. Your hypothesis was close: the #4593 rule answers the enclosing chain's own method before any Kernel builtin, but it answered the base's declared return alone, while the dispatch codegen emits switches over every descendant's override (Post#attributes here) and answers their unified type, sp_RbVal; the older implicit-self arm unified for exactly that reason and the new rule pre-empted it. The unification is one helper shared by both arms now. Your repro is test/rbs-seed/bare_call_override_unify.rb with its sig; the roundhouse tree would be worth a run on your side.

**Comment by webit-wagner** [comment]
Confirmed on both, against `5d23d1e1`:

- the repro compiles and prints `{"a" => "b"}`, matching CRuby;
- roundhouse's `spinel_toolchain` suite passes — 104s to green, where it had been failing at 16s in the C build.

Thanks for the mechanism. My guess had the right place and the wrong direction: I assumed the rule preferred the enclosing class's own BODY over the declared type, when it was answering the declared return alone and pre-empting the unification the implicit-self arm was doing. Good to know the two arms share one helper now.
