### ISSUE TITLE
[Compiler] Forwarding `(*args, **kwargs)` into a method with a `**rest` keyword parameter aborts C compilation

### ISSUE THREAD

**Issue by KieranP** [matz/spinel#3176]
> (Disclaimer: I asked Claude Opus 4.8 to find Spinel compile/runtime issues with documented Ruby classes and methods. It found the following issue, which I manually verified for accuracy before publishing this report)

_Reproduced with `spinel 14ead3d20a9b` vs `ruby 4.0.3`._

A method that captures a keyword-rest (`**extra`) compiles fine on its own, but when it is called via `build(*args, **kwargs)` from a wrapper whose own signature is `(*args, **kwargs)`, Spinel passes the internal `sp_SymPolyHash` keyword hash where a plain `sp_RbVal` value is expected and the C compiler rejects the program. Forwarding without the leading `*args`, or into a method with only named keywords, both compile.

## Repro

```ruby
def build(name, **extra)
  "#{name}/#{extra.size}"
end
def wrapper(*args, **kwargs)
  build(*args, **kwargs)
end
puts wrapper("dave", role: "dev")
```

Ruby: `dave/1`
Spinel: C compilation failed (see below)

## Compile error

```
20260721201216769_kwargs-splat-forward-to-keyword-rest.rb:13:72: error: passing 'sp_SymPolyHash *' (aka 'struct sp_SymPolyHash *') to parameter of incompatible type 'sp_RbVal'
1 error generated.
spinel: C compilation failed
```

**Comment by matz** [comment]
Fixed in d27ba158. The collected keyword-rest hash is now boxed (sp_box_obj / SP_BUILTIN_SYM_POLY_HASH) when the callee's `**rest` param is typed poly, so `build(*args, **kwargs)` forwarding into `def build(name, **extra)` compiles and matches the C signature.
