### ISSUE TITLE
update spinel and LangArena stop compiles

### ISSUE THREAD

**Issue by kostya** [matz/spinel#4204]
script: https://github.com/kostya/LangArena/blob/master/ruby/main.rb
after update spinel from 02f2064fd8ab to latest master e92579fc498456d2f14df0cfc82cc5ed9f953c9a, langarena stop compiles.

```
spinel main.rb
main.rb:2492: error: passing 'sp_RbVal' to parameter of incompatible type 'sp_int' (aka 'long')
/Users/kostya/projects/spinel/bin/../lib/spinel_rt.h:3726: note: passing argument to parameter 'i' here
main.rb:2493: error: passing 'sp_RbVal' to parameter of incompatible type 'sp_int' (aka 'long')
/Users/kostya/projects/spinel/bin/../lib/spinel_rt.h:3726: note: passing argument to parameter 'i' here
main.rb:263: error: unexpected type name 'sp_RbVal': expected expression
main.rb:263: error: expected ';' at end of declaration
main.rb:264: error: use of undeclared identifier '_t619'
main.rb:265: error: use of undeclared identifier '_t619'
```

bisect show that problem appears in f0a93f3d7de67e199ed3ec2d64ebe8bb9f5b9b22.

**Comment by matz** [comment]
Fixed in HEAD -- main.rb compiles again, and the benchmarks over the affected paths (Binarytrees::Arena, Maze::BFS, Etc::CacheSimulation, Calculator::Interpreter, Etc::Sieve) answer OK with CRuby's checksums here.

Thank you for the bisect; it pointed exactly right. f0a93f3d makes a call through a poly receiver carry a type BOTH its arms can hold -- your `Calculator::Int64#to_i` means every `.to_i` on a value that is only known at run time must be able to answer an Int64's result too, so more slots ride boxed than before. That widening is correct, but it marched two emitters into shapes they had never met:

1. `@result += sum(0)` on a slot that may hold an Int64 (the user `+` dispatch) hoisted its RHS temp by starting the declaration line and THEN emitting the RHS -- whose own argument temps also flow through the prelude, splicing whole statements into the half-written initializer. That is your `unexpected type name 'sp_RbVal'` at main.rb:263. The same arm also re-emitted the RHS in its numeric fallback, which would have called `sum` twice per `+=`; both arms fold one evaluated temp now.
2. `cell.neighbors[i], cell.neighbors[j] = ...` in Maze#update_neighbors passed the widened `i`/`j` (boxed, via Helper.next_int's widened return) straight into the typed array set's sp_int slot -- your two errors at main.rb:2492-2493. The multiple-assignment index target unboxes now, as its boxed-receiver sibling always did.

One honest note on performance rather than correctness: because Int64 defines `to_i`/`+`/`%`, calls to those names through untyped values box more than they did before f0a93f3d, and Helper.next_int's signature is one of the places that shows. The checksums are right and the timings here still beat CRuby comfortably on every benchmark I ran, but if you see a regression against the numbers you had at 02f2064f, file it with the bench name and I will look at narrowing the widening.

**Comment by kostya** [comment]
thanks, most regressed from 02f2064fd8abf46ce9acd05e582c9d9acad9a447, `CLBG::Mandelbrot`, 0.937s -> 8.408s, ~9x.
