### ISSUE TITLE
A class method called from inside a lifted block passes an _sp_cls that is not in scope

### ISSUE THREAD

**Issue by rubys** [matz/spinel#3797]
`c357050d` ("Construct through a Class value read out of a container") gives an inherited class method the receiving class as a leading `sp_Class _sp_cls` parameter. When a sibling class-method call is emitted from inside a **lifted block**, the call site writes the bare identifier `_sp_cls` — but a lifted proc's signature is `(void *_cap, mrb_int argc, mrb_int *args)`, and its capture struct holds only the block's own captures. The identifier is not in scope, so the C compiler rejects it.

Bisected to `c357050d` over `708ffbe9..9a6a9e1f`.

## Reproduction

```
curl -sL https://roundbench.showcase.party/lobsters/spinel-tree.tgz | tar xz
cd transpiled-lobsters-spinel
# the manifest pins bcrypt to the bench box's path; point it at a checkout
# of https://github.com/rubys/spinel-bcrypt (or drop the line once the
# index entry lands: matz/spin-index#5)
$EDITOR spin.toml     # line 7: bcrypt = { path = "..." }
spin build
```

Verified just now against a freshly-built `9a6a9e1f0224`:

```
app/models/application_record.rb:27:72: error: use of undeclared identifier '_sp_cls'
   27 |       _sp_proc_poly_ret = (sp_ApplicationRecord_s_preload_associations(_sp_cls, (*((_proc_cap_48 *)_cap)->records), …
app/models/application_record.rb:30:71: error: use of undeclared identifier '_sp_cls'
app/controllers/messages_controller.rb:269:44: error: use of undeclared identifier '_sp_cls'
```

The Ruby is 14 lines (`app/models/application_record.rb`), a class method calling siblings from inside a block:

```ruby
class ApplicationRecord < ActiveRecord::Base
  def self._preload_dispatch(records, name, nested)
    nil
  end

  def self.preload_associations(records, specs)
    return if records.length == 0
    specs.each do |spec|
      if spec.is_a?(Hash)
        spec.each do |name, nested| _preload_dispatch(records, name, nested) end
      else
        if spec.is_a?(Array)
          preload_associations(records, spec)
        else
          _preload_dispatch(records, spec, nil) if !(spec.nil?)
        end
      end
    end
    nil
  end
end
```

## Emitted C

```c
typedef struct { sp_RbVal *records; } _proc_cap_48;          /* no _sp_cls */
static void _proc_cap_scan_48(void *p) { … }

static mrb_int _proc_48(void *_cap, mrb_int argc, mrb_int *args) {
  …
  _sp_proc_poly_ret = (sp_ApplicationRecord_s_preload_associations(
      _sp_cls,                                               /* undeclared */
      (*((_proc_cap_48 *)_cap)->records), …), sp_box_nil());
```

`_sp_cls` reaches the body from the `cmethod_takes_self_cls(encl)` arm — `encl` is still the class method while the code is being emitted into the lifted proc, so the "forward ours" branch is taken and there is nothing to forward. It looks like `_sp_cls` wants to ride into `_proc_cap_N` the way `records` does, which is why I'm filing rather than sending a patch — that's your capture machinery.

## I could not source-reduce this

Every standalone I wrote compiles, because the block gets **inlined**: `spinel -c` output has `_proc_cap` count 0. I tried subclass present + body mentions `self` + sibling call inside a nested block + an outer parameter captured + poly receivers + two differently-typed call sites; none of them stopped spinel from inlining the block, so the lifted-proc path was never reached. Whatever forces the block to be materialized in the real tree (there `lv_specs` is `sp_RbVal` and `each` goes through a runtime `cls_id` switch, including `sp_ActiveRecord__Result_each_pf`) I could not synthesize. If you know the shortest way to force a capture-carrying proc, I'll happily turn that into a `test/` case.

## Context

Found because all four AOT lanes of the lobsters benchmark stopped building. Separately, `f1edaed6` broke us in a second way — a valueless argument sequenced into `void _tN = …` — which I've sent as #3796 with a 6-line repro.
