### ISSUE TITLE
[Compiler] A local bound from an Array[Integer] element is typed String when the expression also indexes a String constant (cead44bb)

### ISSUE THREAD

**Issue by rubys** [matz/spinel#3971]
A local bound from an `Array[Integer]` element is typed `String` when the same
expression also indexes a `String` constant. The integer arithmetic on it then
compiles to `sp_raise_nomethod(... "undefined method '&' for an instance of
String" ...)`, which lands in an `mrb_int` argument slot and fails the C build.

Bisected to cead44bb ("Alias the element a string read out of a container
binds"); its parent 39cc2af2 is clean.

## Reproduce

Self-contained — a published archive, no other checkout needed:

```sh
curl -fsSL https://rubys.github.io/roundhouse/browse/spinel.tgz | tar -xz
cd spinel
make build          # → spinel main.rb --rbs . -o build/blog
```

```
39cc2af2 (parent of cead44bb)   make build → OK
cead44bb                        make build → 13 errors in runtime/base64.rb, exit 2
master (39b2baca)               same 13 errors
```

I could not reduce this below the whole program: `runtime/base64.rb` compiled
on its own is clean at cead44bb, as is a hand-cut version of the method. It
needs the surrounding program, which is why the archive is the repro.

## The source

`runtime/base64.rb`, `Base64.strict_encode64`:

```ruby
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

def self.strict_encode64(s)
  bytes = s.bytes        # Array[Integer]
  n = bytes.length
  out = +""
  i = 0
  while i + 3 <= n
    b0 = bytes[i]
    b1 = bytes[i + 1]
    b2 = bytes[i + 2]
    out << ALPHABET[(b0 >> 2) & 0x3F].to_s
    ...
```

Two containers meet in one expression: `bytes` is `Array[Integer]` and
`ALPHABET` is a `String`.

## What is emitted

```
runtime/base64.rb:26:11: error: incompatible integer to pointer conversion
  assigning to 'sp_String *' from 'mrb_int' (aka 'long') [-Wint-conversion]
   26 |       b0 = bytes[i]
```

so `b0` is declared `sp_String *`. The arithmetic on it then becomes a raise:

```c
sp_String_append_bin(lv_out, ({ const char *_t367 =
  sp_str_char_at_or_nil(cst_ALPHABET,
    sp_raise_nomethod(sp_stage_args_msg(
      "undefined method '&' for an instance of String", 1,
      (sp_RbVal[]){sp_box_int(63LL)})));
  _t367 ? _t367 : SPL(""); }));
```

```
runtime/base64.rb:29:93: error: passing 'sp_RbVal' to parameter of
  incompatible type 'mrb_int' (aka 'long')
lib/sp_str.h:151:55: note: expected 'mrb_int' but argument is of type 'sp_RbVal'
  151 | const char*sp_str_char_at_or_nil(const char*s,mrb_int i);
```

The C diagnostic is downstream; the compiler has already decided `b0` is a
String, which is what the `"undefined method '&' for an instance of String"`
message says. Earlier occurrences in the same method say `"for unknown"` and
later ones say `"for an instance of String"`.

## Theory

Guessing from the commit title, the alias that binds a string element read out
of a container is reaching `b0`, which is read out of a *different* container in
the same expression tree — `ALPHABET[...]` is the string read, `bytes[i]` is
not.

## Environment

```
spinel cead44bba976 [Apple clang version 21.0.0 (clang-2100.1.1.101)]
```

Also reproduces on Linux/gcc in CI (ubuntu-latest, GitHub Actions).
