### ISSUE TITLE
Regression (cb23cc6): spinel_kit+tep deps build fails -Wint-conversion — string ivar/param collapses to mrb_int (compile error, cf #1382 runtime)

### ISSUE THREAD

**Issue by OriPekelman** [matz/spinel#1394]
## Summary

Building **spinel_kit 0.1.0** together with **tep 0.11.2** under spinel **`cb23cc6`** fails the C compile with `-Wint-conversion` errors: string-valued ivars/params are typed `const char *` at the slot but the assigned value arrives as `mrb_int`. This is a **build-breaking compile failure** (clang `-Werror`), distinct from the *runtime* miscompile in #1382 (which compiles but emits pointer-as-int).

It blocks toy's HTTP serving path on macOS (toy#27) once the deps bundle (`spinel_kit` + `tep`) is compiled together.

## Errors (real build, `make tep_demo/hello` → spinel on the vendored deps)

```
spinel_kit/lib/spinel_kit/log.rb:36:24: error: incompatible integer to pointer
  conversion assigning to 'const char *' from 'mrb_int' (aka 'long')   # @min_level = name
spinel_kit/lib/spinel_kit/log.rb:37:24: error: ... assigning to 'const char *' from 'mrb_int'   # @file_path = path
spinel_kit/lib/spinel_kit/json_builder.rb:125:54: error: incompatible integer to pointer
  conversion passing 'mrb_int' (aka 'long') to parameter of type 'const char *'
... 6 errors generated. spinel: C compilation failed
```

`log.rb` source (the failing lines are the ivar writers):
```ruby
class Log
  attr_accessor :min_level, :file_path
  def initialize; @min_level = "info"; @file_path = ""; end
  def set_level(name); @min_level = name; end   # :36 — name typed mrb_int
  def to_file(path);   @file_path = path; end    # :37 — path typed mrb_int
  def should_log?(level); Log.level_value(level) >= Log.level_value(@min_level); end
  def self.level_value(name)                      # name compared == "debug" -> returns Int
    ...
  end
end
```

## Narrowing

- **`log.rb` compiles cleanly on its own** (standalone driver, with or without `--rbs sig`). The bare ivar pattern (`@min_level = "info"; def set_level(n); @min_level = n; end`) also compiles in isolation.
- The failure appears **only when the full deps bundle (`spinel_kit` + `tep`) is compiled together**. That points at a **whole-program type unification collapse**: the param names `name` / `path` (and the byte/char in `json_builder.rb`) carry an `Int` type at some *other* site in the bundle, and the slot for these string ivars/params collapses to `mrb_int` — the local-name-collapse class.
- Likely interacting with the recent ivar-typing rework: `7c55756` "Type an ivar-write expression by the ivar slot, not the int default" and its follow-up `3f4652a` "Keep ir_set_sa_ivar int-typed…" (which patched one `-Wint-conversion` fallout in the self-host build but not this consumer case).

## Related

- #1382 — `from_str_hash` Hash-block param loses String type → pointer-as-int **at runtime** (compiles). Same family (String→pointer-as-int), but that one builds; this one fails the build.
- #1386 — another `cb23cc6` regression.
- Downstream: tep#201, tep#205, toy#27 (serving path).

## Environment

- spinel `cb23cc6` (`+dirty`), arm64-darwin, clang.
- spinel_kit 0.1.0, tep 0.11.2 (released gems, vendored via spinelgems).

**Comment by OriPekelman** [comment]
**Toolchain context (post-filing).** This was observed on the **shared `~/sites/spinel` checkout at `cb23cc6`** (matz/spinel master HEAD). The downstream consumer (toy) does *not* track master — it pins specific revs (current canonical: `a699cf9` on the `fix/poly-array-concrete-array-boundary` branch). I have **not** reproduced this against `a699cf9`, where the serving/deps path that surfaced it is de-scoped on macOS.

So: still a valid **spinel-master** regression report, but not a blocker on toy's pinned toolchain. Flagging in case the ivar-typing rework (`7c55756` / `3f4652a`) lands differently on the two lineages.

**Comment by matz** [comment]
Thanks for the detailed report and for publishing spinel_kit, which let me reproduce the exact bundle. The short version: this does not reproduce on current master, and the cited commit puts the original failure in the legacy (Ruby) backend rather than the C driver.

## Reproduction on current master

I vendored spinel_kit into a tep example and built `spinel_kit + tep` together through tep's own harness (full tep lib inlined, 221 namespace hits confirming both trees are present). The whole-program C compiles with **0 errors and 0 `-Wint-conversion` warnings**, and the methods you flagged are emitted with the right types:

```c
sp_Log_set_level(sp_Log *self, const char * lv_name)   // name is const char*, not mrb_int
sp_Log_to_file  (sp_Log *self, const char * lv_path)   // path is const char*
sp_Builder_s_hex2(mrb_int lv_n)                         // n is mrb_int, called with the int byte
```

Both `SpinelKit::Log` and the namesake `Tep::Logger` coexist and type correctly.

## Why the commit reference points at the legacy backend

The build you hit was at `cb23cc6` (+dirty), and that commit predates the C driver entirely:

- At `cb23cc6` (Jun 8) there is no `src/` tree at all. The code generator is `spinel_codegen.rb` and the analyzer is `spinel_analyze.rb` -- the legacy Ruby backend.
- The C sources land later: `src/analyze.c` at `6152b69` and `src/codegen_call.c` at `e2e1b79`, both on Jun 12, four days after `cb23cc6`.
- The fix you flagged as adjacent, `7c55756` ("Type an ivar-write expression by the ivar slot"), modifies `spinel_analyze.rb` -- also the legacy backend.

So the `-Wint-conversion` here was emitted by the legacy Ruby code generator, not the C driver (the "spinelc" in the title looks like a transition-period mix-up; #1409, by contrast, bisects to the Jun 12+ C commits and is a genuine C-driver bug, now fixed in `da3014b`).

The legacy backend has since been retired (preserved on the `self-host` branch; master is the C version as of the Jun 15 promotion). Since the maintained codebase builds the real bundle cleanly with correct types, I'm closing this as resolved on current master.

If you re-pin onto current master and any string ivar/param still collapses to `mrb_int` in your bundle, please reopen with the `-S` output around the failing site and I'll dig straight in. The #1409 fix should also unblock the tep re-pin you were chasing here.
