### ISSUE TITLE
`self.attr ||= <array>` through a hand-written writer emits ill-typed C (unboxed value into RbVal param) — incomplete half of the #4148 fix (eb6010e0)

### ISSUE THREAD

**Issue by rubys** [matz/spinel#4277]
`self.attr ||= <array>` through a hand-written `def` writer emits ill-typed C — the value reaches the `sp_RbVal` writer parameter unboxed. Introduced by eb6010e0 (the fix for #4148), which correctly started calling the writer but does not box a concrete-typed right-hand side into it.

## Reproduction

`repro.rb`, entire, no requires, no RBS:

```ruby
class U
  def initialize
    @h = {}
  end

  def g
    @h["k"]
  end

  def g=(v)
    @h["k"] = v
  end
end

u = U.new
u.g ||= []
u.g.push(1)
puts u.g.length
```

```
$ ruby repro.rb
1

$ spinel repro.rb -o repro          # HEAD cdf83a4a
repro.rb:17: error: initializing 'sp_RbVal' with an expression of incompatible type 'sp_IntArray *'
spinel: C compilation failed
```

(`repro.rb:17` is the `u.g ||= []` line.)

## Bisect

`git bisect` over the compile (good = compiles, bad = C error) lands on:

```
eb6010e0  Call the writer for `obj.attr ||= v` when it is a real def
```

That commit is the fix for #4148: before it, `self.attr ||= v` touched the ivar directly and skipped a hand-written writer. It now routes through the writer — verified in the emitted C, `sp_U_g_set(sp_U *self, sp_RbVal lv_v)` is called on the assigning branch. What is missing is the boxing of the value into that `sp_RbVal` parameter when the value has a concrete container type: the `[]` (inferred `sp_IntArray *` from the later `push(1)`) is passed straight in, so the C is `sp_RbVal = sp_IntArray *`.

- `eb6010e0^` compiles the repro (its runtime is the #4148 behavior — the writer is never called, so `u.g` reads back `nil` and `.length` raises `NoMethodError`; that is exactly what eb6010e0 set out to fix).
- `eb6010e0` and every revision through HEAD fail to compile it.

So this is the incomplete half of the #4148 fix rather than a new regression in spirit: the writer call is right, the argument conversion at the call is not. `attr = v` and `attr += v` were already boxing correctly; only the short-circuit `||=` / `&&=` forms take the new path.

## Where it turned up

A real app (a Rails-shaped tree) has `self.keybase_signatures ||= []` on a store-backed accessor whose writer takes an untyped value; it compiled through eb6010e0^ and stops at the C error now. Minimized to the above.

**Comment by matz** [comment]
Fixed in b69f61fd.

Your bisect landed on the right commit and the diagnosis was one step from the cause. It is not the writer call's argument that is unboxed: it is the temp the value is spilled into on the way there. eb6010e0 declares that temp from `comp_ntype` of the right-hand side, and an empty container literal has no type of its own -- `comp_ntype` answers poly, while the emitter picks the concrete container from how the attribute is used later. So the declaration said `sp_RbVal _t5` and the initializer said `sp_IntArray_new()`, which is the error you saw. The value is now rendered into the slot the declaration promises.

Found while confirming it, and fixed in the same commit because it is the same line and the same mechanism: a literal nil declared a `void` temp, since emit_ctype spells TY_NIL that way. `u.g ||= nil` is nil in CRuby, so TY_NIL joins the unknown/void fallback to poly.

`||=` and `&&=` now agree with CRuby for `[]`, `{}`, nil, a non-empty array, a string, an integer and an object, twelve combinations checked against ruby directly, and the writer still runs exactly once on the assigning branch and not at all on the other. test/call_or_write_writer_boxes_value.rb covers it; make gate is green (3410 pass).

Your framing was right that this is the incomplete half of #4148 rather than a regression in spirit: `attr = v` and `attr += v` never took this path.
