### ISSUE TITLE
codegen: class-method call on an sp_RbVal (untyped) receiver emits an unconditional sp_raise_nomethod instead of dispatching

### ISSUE THREAD

**Issue by rubys** [matz/spinel#3215]
Gap: a class-method (singleton-method) call through a receiver whose static type is `untyped` (C type `sp_RbVal`) is compiled to an unconditional `sp_raise_nomethod(...)` — even when the value at runtime is a class that defines the method. The program raises `NoMethodError` instead of dispatching.

## Repro

`repro.rb`:

```ruby
class Article
  def self.table_name
    "articles"
  end
end

class Relation
  def initialize(model)
    @table = model.table_name   # `model` is untyped (sp_RbVal); table_name is a class method
  end

  def table
    @table
  end
end

puts Relation.new(Article).table
```

`sig/repro.rbs` (pins `model` to `untyped`):

```rbs
class Relation
  def initialize: (untyped model) -> void
  def table: () -> String
end
```

```
$ spinel --rbs sig repro.rb -o repro && ./repro
```

## Observed (current master `b75d810a`)

```
undefined method 'table_name' for an instance of Class (NoMethodError)
```

CRuby prints `articles`. The emitted C for `Relation#initialize` compiles `model.table_name` to an unconditional raise — there is no dispatch:

```c
static void sp_Relation_initialize(sp_Relation *self, sp_RbVal lv_model) {
  self->iv_table = (sp_raise_nomethod(
      sp_nomethod_msg_args("table_name", lv_model, 0, (sp_RbVal[]){sp_box_nil()})),
      sp_box_nil());
}
```

## Expected

Prints `articles` — the class-method call dispatches at runtime on the boxed class value (the same way instance sends on an `sp_RbVal` receiver already do).

## First bad commit

Bisected (clean per-commit rebuilds) to `a8bec8f7` ("analyze: --rbs seeds were silently dropped for unions and collision-renamed classes"); parent `d746d051` is good. Both endpoints verified with fresh rebuilds.

`a8bec8f7` is a correct fix — it adds the missing arm for the bare `poly`/union seed tag, so `untyped`/union seeds that were previously dropped now apply. Once `Relation#initialize`'s `(untyped model)` seed is honored, `model` is a real `sp_RbVal` and `model.table_name` exposes this latent codegen gap. The gap, not the seed fix, is the defect.

## Precedent

Same species as #1819 → #1827 — a correct RBS type fact that spinel now honors, exposing an incomplete codegen boundary. #1827 settled that the resolution is to **honor the annotation and complete the codegen at the boundary**, not to reject/drop the correct type. Here the boundary is the **receiver** of a class-method send: honor the `sp_RbVal` and dispatch, rather than emitting an unconditional `sp_raise_nomethod`.

Related lineage: #2445 (method dispatch on a Class-typed receiver) covered the *statically-known* class-object case; this is the case where the class value is carried as an `sp_RbVal`.

(Real-world origin: roundhouse's `ActiveRecord::Relation#initialize(model)` holds the model class as a plain class-object value typed `untyped`, then computes `@table = model.table_name` — so every `Relation.new(SomeModel)` now raises.)

**Comment by matz** [comment]
Fixed in 1423fba9. A method call on an untyped receiver whose name is a class method now dispatches on the runtime class tag (e.g. `model.table_name` when `model` holds `Article`), instead of emitting an unconditional NoMethodError.
