### ISSUE TITLE
codegen: poly virtual-dispatch passes an unboxed scalar arg to an override branch whose param is sp_RbVal

### ISSUE THREAD

**Issue by rubys** [matz/spinel#3214]
Gap: a virtual (`cls_id`-switch) dispatch over an override family whose branches were monomorphized to **different parameter C-types** passes the *same* argument temp to every branch, unboxed. The branch whose parameter is the wider `sp_RbVal` receives a raw scalar (`sp_sym` / `mrb_int`), which aborts the C build.

Contravariant parameter widening in an override is Liskov-legal (a subclass may accept a wider input), so both signatures are individually valid; only the dispatch site is wrong.

## Repro

`repro.rb`:

```ruby
class Base
  def act(name)
    raise "not implemented"
  end
end

class Sub < Base
  def act(name)
    name.to_sym
    99
  end
end

s = Sub.new          # keeps Sub's branch live in the vtable
s.act("go")

bare = Base.new      # static type Base -> virtual dispatch over {Base, Sub}
bare.act(:ok)        # :ok is a symbol literal -> sp_sym
```

`sig/repro.rbs` (pins the divergent parameter types):

```rbs
class Base
  def act: (Symbol name) -> void
end

class Sub < Base
  def act: (untyped name) -> untyped
end
```

```
$ spinel --rbs sig repro.rb -o repro
```

## Observed (current master `b75d810a`)

```
repro.rb:21:151: error: passing 'sp_sym' (aka 'long') to parameter of incompatible type 'sp_RbVal'
   21 |   ({ mrb_int _t6; switch ((lv_bare)->cls_id) { case 0: _t6 = sp_Base_act((sp_Base *)lv_bare, _t5); break; case 1: _t6 = sp_Sub_act((sp_Sub *)lv_bare, _t5); break; default: _t6 = sp_Base_act((sp_Base *)lv_bare, _t5); break; } _t6; });
      |                                                                                                                                                       ^~~
repro.rb:8:50: note: passing argument to parameter 'lv_name' here
    8 | static mrb_int sp_Sub_act(sp_Sub *self, sp_RbVal lv_name) {
      |                                                  ^
spinel: C compilation failed
```

`_t5` is the symbol argument (`sp_sym`). The two monomorphized signatures:

```c
static mrb_int sp_Base_act(sp_Base *self, sp_sym   lv_name);   // Symbol  -> sp_sym
static mrb_int sp_Sub_act (sp_Sub  *self, sp_RbVal lv_name);   // untyped -> sp_RbVal
```

The `case 1` branch passes `_t5` (an `sp_sym`) straight into `sp_Sub_act`'s `sp_RbVal` parameter with no boxing. `Integer` behaves identically (`mrb_int -> sp_RbVal`), so the gap is general to any scalar → `sp_RbVal` widening across the override set.

## Expected

Compiles; the switch coerces the argument to each branch's declared parameter type — boxing the scalar into `sp_RbVal` for the branch that expects it.

## First bad commit

Bisected (clean per-commit rebuilds) to `a8bec8f7` ("analyze: --rbs seeds were silently dropped for unions and collision-renamed classes"); parent `d746d051` is good. Both endpoints verified with fresh rebuilds.

`a8bec8f7` is a correct fix — it starts honoring `--rbs` seeds previously dropped for the collision-renamed `*::Base` classes. Honoring the base's `(Symbol)` param seed while the subclass override stays `untyped` is what makes the two branches' parameter C-types diverge and exposes this latent poly-dispatch codegen gap. The gap, not the seed fix, is the defect.

## Precedent

This is the **argument-boundary** analog of #1819 → #1827 (the *return*-boundary case): a poly value flowing into a slot with a concrete type from a correct RBS annotation. #1827 settled that the right resolution is to **honor the annotation and materialize/coerce at the boundary** (there: `sp_StrArray_from_poly_array`), not to reject the correct type. The same resolution applies here — box the scalar into `sp_RbVal` per dispatch branch.

Closely related to #3203 (override-family self-class **return** seeds); this is the **parameter** facet of the same override-family poly-dispatch shape.

**Comment by matz** [comment]
Fixed in 8581b12c. Each virtual-dispatch arm now coerces the shared argument temp to that override's declared parameter type (boxing a concrete value into an `untyped`/sp_RbVal param, unboxing the reverse), instead of passing the base method's type raw to every branch.
