### ISSUE TITLE
An uncalled method is pulled into codegen by a same-named method on an unrelated class

### ISSUE THREAD

**Issue by rubys** [matz/spinel#4340]
`spinel b658debba511` (upstream HEAD at time of writing), macOS, Apple clang 21.

Whether a method body reaches codegen appears to be decided by the method's **name** rather than by its receiver's class. An uncalled method can therefore be pulled into codegen by an unrelated class that happens to define the same name — and if that uncalled body contains a self-call its own chain cannot answer, the program is rejected.

## Repro

```ruby
module RequestDispatch
  def post(path, params: {})
    puts "post " + path + " " + params[:u].to_s
  end
end

class TestBase
end

class IntegrationTest < TestBase
  include RequestDispatch
end

class ModelTest < TestBase
  # Never called. `post` is not in ModelTest's chain.
  def sign_in(user)
    post("/session", params: { u: user })
  end

  def test_it
    puts "model ok"
  end
end

class ControllerTest < IntegrationTest
  # Called. `post` IS in ControllerTest's chain (via RequestDispatch).
  def sign_in(user)
    post("/session", params: { u: user })
  end

  def test_it
    sign_in("dave")
  end
end

ModelTest.new.test_it
ControllerTest.new.test_it
```

```
$ spinel final.rb -o final
spinel: final.rb:17: unsupported call: node 44 (CallNode `post`) recv=-/ty-1 argc=2 arg0ty6
```

Line 17 is `ModelTest#sign_in`, which is never called. CRuby runs the program:

```
$ ruby final.rb
model ok
post /session dave
```

Two controls isolate the trigger:

* **Delete `ControllerTest`** (and its call) — compiles, runs `model ok`. The very same `ModelTest#sign_in` body is accepted.
* **Keep `ControllerTest`, rename its helper** to `sign_in_other` (and its call site) — compiles, runs both lines.

So it is `ControllerTest#sign_in` being called that pulls `ModelTest#sign_in` into codegen.

## Why the shape occurs

It is the ordinary Rails test-helper idiom. In `test/test_helper.rb`:

```ruby
class ActiveSupport::TestCase
  include SessionTestHelper   # defines sign_in, whose body calls `post`
end
```

`post` comes from `ActionDispatch::IntegrationTest`, so `sign_in` is live in controller tests and dead in model tests — and both inherit `ActiveSupport::TestCase`. CRuby never resolves the dead copy.

## Where we hit it

Compiling once-campfire's 54 emitted test programs. Each compiles on its own; several stop compiling as soon as two of them are placed in one program, always on this call. The practical effect is that a per-program result depends on what else is linked in: the same source builds or does not build according to its neighbours.

## Not asking for a particular resolution

Either direction looks self-consistent — restrict codegen reachability to the receiver's own class, or keep compiling the body and defer to the runtime `NoMethodError` spinel already reports elsewhere (`undefined method 'x' for an instance of Y`). The report is about one body getting two answers.

**Comment by matz** [comment]
Fixed in 687074ba. Your diagnosis is exactly right: reachability for codegen is decided by a method's NAME, not by its receiver's class, so a live `ControllerTest#sign_in` pulls `ModelTest#sign_in` into codegen even though nothing can reach it.

Of the two directions you offered, this takes the second: the call emits the NoMethodError CRuby would raise if that body ever ran, and the program builds. A body that IS called reports it at the moment it is called rather than at build time -- which is also what the surrounding gate already does for the zero-argument spelling of the same thing (a bare unresolved identifier is a runtime NameError, #3037). Your repro now prints `model ok` and `post /session dave`, matching CRuby.

I did not narrow reachability to the receiver's class. The name-based walk is a deliberate over-approximation -- a great many receivers have no static class -- and tightening it is a much larger change with a much larger blast radius than the report warrants.

The arm is deliberately narrow, because the risk in this direction is masking real compiler gaps. It takes an implicit self-call with arguments that every emitter declined, whose name the enclosing class's chain does not have, **and** which some user class or module defines somewhere. That last condition is what distinguishes "this receiver is the wrong class for this method" from "the compiler has no arm for this builtin". Both of the loud cases stay loud, and I checked them:

    class C; def go; totally_unknown_name("x"); end; end     # still a compile error
    class C; def go; [1,2].some_missing_builtin(3); end; end  # still a compile error

Since the practical shape is 54 programs that build alone and not in pairs, the case that matters most is the one in the middle: with the fix, the dead copy compiles to a raise nobody executes, the live copy works, and a wrong-class call that really runs raises `NoMethodError` at that point. All three are in the regression test, verified against ruby 4.0.4.
