### ISSUE TITLE
Since 6dfd268e (#4492) the proc-form arm a blockless poly call gains passes its arguments unconverted: `node.fetch("k", "")` on a poly Hash fails to compile against `Cache#fetch(key, opts = {})`

### ISSUE THREAD

**Issue by rubys** [matz/spinel#4497]
Follow-up to #4492, whose fix (6dfd268e) is right about what it fixed — `Net::HTTP#request` through a poly receiver reaches its entry again — and campfire now needs one more thing from the arm it adds.

A blockless `.fetch(k, default)` on a poly receiver that holds a Hash at run time now carries an arm for every yielding `fetch` that inlines elsewhere. campfire's `Rails::Cache#fetch(key, opts = {})` is one, and its arm passes the call's second argument — a String — straight into `opts`, whose C parameter is `sp_SymPolyHash *`. The program does not compile.

```ruby
# Since 6dfd268e a blockless poly-receiver call also gets the proc-form
# arm of every method of the name that yields and inlines elsewhere.
# Cache#fetch(key, opts = {}) yields; a `.fetch(k, default)` on a poly
# Hash now carries an arm for it, whose second argument is passed to
# `opts` — a Hash parameter — unconverted.
class Cache
  def initialize
    @entries = {}
  end

  def fetch(key, opts = {})
    yield
  end
end

def warm(c)
  c.fetch("x", expires_in: 60) { "computed" }
end

slots = { "a" => { "__name" => "action-text-attachment", "sgid" => "abc" }, "b" => { "__name" => "b" } }
nodes = [slots["a"], slots["b"]]
found = 0
nodes.each do |node|
  found += 1 if node.fetch("__name", "") == "action-text-attachment"
end
puts found
puts warm(Cache.new)
```

```
$ ruby pf_arm_arg_conv2.rb
1
computed

$ spinel pf_arm_arg_conv2.rb -o t          # master a4ecc3b6
pf_arm_arg_conv2.rb:24: error: passing 'sp_RbVal' to parameter of incompatible type 'sp_SymPolyHash *' (aka 'struct sp_SymPolyHash *')
spinel: C compilation failed

$ spinel pf_arm_arg_conv2.rb -o t          # 1fe20889, the commit before
1
computed
```

Bisected on campfire: `git bisect run` over `1fe20889..6dfd268e` compiling `test/models/account_test.rb` names 6dfd268e. Every one of campfire's 54 test files fails to link on master for this site (`runtime/action_text.rb:631`, `out << Attachment.new(node) if node.fetch("__name", "") == …`) and one more (`app/controllers/rooms/closeds_controller.rb:98`), both `.fetch` with a String default on a poly Hash; the note points at `sp_Cache_fetch_pf(…, sp_SymPolyHash *lv_opts, sp_Proc *)`.

Two observations on the shape rather than a proposal: the same site at 1fe20889 dispatched `fetch` over the Hash kinds, Flash, Session and Cache's non-proc form with `sp_box_str("")` for the String; and the new arm is dead at this site in every program — a Hash never IS a Cache — which is what #4218's "a switch with only default:" reading said from the other side: an arm the candidate search adds for a receiver kind the site cannot hold still has to type-check.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01GTHXBDXH9EohRcenKAUSfF

**Comment by matz** [comment]
Fixed in 9e7c4b6a, which went out an hour after 6dfd268e when campfire stopped building on exactly this site (`cookies.fetch("flash_notice", "")` against Cache#fetch). The arm's compatibility test and its argument spelling read the method's original scope, whose `opts` had stayed untyped since it only ever inlined; they now read the proc form's own parameters, so the String drops the Cache arm the way an incompatible argument drops any other, and the dispatch is the one 1fe20889 emitted plus the arms that can take the call. Your reproduction prints 1 / computed on master 71f076a2, and campfire builds and serves.
