### ISSUE TITLE
An ivar Array[String] stores a `<<`-built string as a struct pointer — silent corruption

### ISSUE THREAD

**Issue by rubys** [matz/spinel#3400]
Pushing a `<<`-built string into an **ivar** `Array[String]` stores the `sp_String*` struct pointer into a slot typed `const char*`. The C compiler flags the mismatch as a warning, so the build links and the value reads back as garbage — no exception, no crash, wrong bytes.

## Repro

```ruby
class Holder
  attr_accessor :items
  def initialize
    @items = [""]      # type seed; a bare [] infers sp_IntArray
    @items.pop
  end
end
h = Holder.new
s = +""
s << "b"
s << "=2"
puts "before push: " + s          # expect b=2
h.items << s
puts "after push:  " + h.items[0] # expect b=2
h.items.each { |x| puts "in each:     " + x }
```

Actual:

```
before push: b=2
after push:  <garbage>
in each:     <garbage>
```

Expected: `b=2` on all three lines. (CRuby prints `b=2` three times.)

## What the compiler says

`spinel min.rb` emits a warning and links anyway:

```
min.rb:13:38: warning: incompatible pointer types passing 'sp_String *' to
              parameter of type 'const char *' [-Wincompatible-pointer-types]
   13 |   sp_StrArray_push((lv_h)->iv_items, lv_s);
      |                                      ^~~~
lib/sp_array.h:170:62: note: passing argument to parameter 'v' here
  170 | static inline void sp_StrArray_push(sp_StrArray*a,const char*v){...}
```

`sp_StrArray` holds `const char*`. A `<<`-built string is an `sp_String*`. The push site passes it through without a conversion, so `a->data[a->len++]` receives a struct pointer and later reads treat those bytes as characters.

## Both conditions are needed

Three neighbouring shapes compile clean, with no warning and correct output — only the combination fails:

| array | pushed string | result |
|---|---|---|
| **ivar**, seeded `[""]` + `pop` | **`<<`-built** | **garbage** |
| local, seeded `[""]` + `pop` | `<<`-built | ok |
| ivar, seeded `[""]` + `pop` | `+`-built (`"b" + "=2"`) | ok |
| ivar, seeded `[""]` + `pop` | literal (`"b=2"`) | ok |

The seed idiom itself is not optional here: with `@items = []` the ivar infers `sp_IntArray` and pushing a String is a hard error (`incompatible pointer to integer conversion passing 'const char *' to parameter of type 'mrb_int'`), so `[""]` + `pop` is the way to declare the element type.

## Where this was hit

An `Array[String]` ivar holding fully-formatted `Set-Cookie` lines, filled by `<<`-built strings. Reading an element back and calling `String#index` on it raised `NoMethodError: undefined method 'index' for an instance of String` — the corrupted slot no longer presents as a string to method dispatch, so the symptom surfaces far from the push.

## Environment

- spinel `4803e38e` (built from source)
- macOS, Darwin 25.5.0 arm64
- Apple clang 21.0.0 (clang-2100.1.1.101)

**Comment by rubys** [comment]
Bisected — this is a regression, first bad commit `37c8464f`:

```
16d6433c  Spliced block bodies emit at their definition-site rename depth   GOOD
37c8464f  Shared strings: every in-place mutator, bang-only aliases,        BAD
          non-literal writes                              (2026-07-23, Refs #3227)
```

`16d6433c` is `37c8464f`'s direct parent, so the boundary is exact. Both endpoints were re-run explicitly after the bisect rather than taken from the bisect result alone. The repro was already failing 25, 100 and 400 commits back from current `main`, so it has been live since 07-23 rather than arriving in the last day.

## Why that commit fits

`37c8464f` widens which strings carry the shared/mutable representation — from its own message, "the fresh-literal-writes-only restriction is dropped (frozen inheritance makes non-literal writes sound)". So `s = +""; s << "b"` now yields an `sp_String*` where it previously would have been a plain `const char*`.

`sp_StrArray_push(sp_StrArray*, const char*)` was not updated to take that representation, and the push site emits no conversion:

```
warning: incompatible pointer types passing 'sp_String *' to
         parameter of type 'const char *' [-Wincompatible-pointer-types]
   sp_StrArray_push((lv_h)->iv_items, lv_s);
```

The commit touches `emit_array_call` (`src/codegen_call_recv.c`, +78) and `emit_array_mutate_stmt` (`src/codegen_stmt.c`, +42), which is the neighbourhood, but the element-push path appears to have been missed.

`test/issue_3227_full_mutators.rb` covers the mutators and the alias pairs, but not pushing a mutated string into an **ivar** `Array[String]` — which is the one shape that fails. A local array with the same push is fine, which is probably why it slipped through.

## Bisect method

Detached worktree off `main`, `vendor/` shared from the primary checkout, ~6s per build. Test = compile the repro, run it, compare line 2 to `after push:  b=2`.
